### ISSUE TITLE
Script attempts to match directories

### ISSUE THREAD

**Issue by tikonen** [veeraene/find_same_files#1]
```
C:\projects>find_same_files.py c:\work pdf
Traceback (most recent call last):
  File "C:\projects\find_same_files.py", line 100, in <module>
    main()
  File "C:\projects\find_same_files.py", line 93, in main
    files_with_same_content = find_same_files(sys.argv[1], sys.argv[2])
  File "C:\projects\find_same_files.py", line 45, in find_same_files
    with open(file_name, 'rb') as file:
PermissionError: [Errno 13] Permission denied: 'c:\\work\\UE\\Engine\\Documentation\\Source\\GettingStartedPDF'
```
Script should only try to match normal files.

**Comment by veeraene** [comment]
Now it checks if the path is a regular file.
